import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import Title from "@/components/Title";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div>
      <div className="">
        <div className="h-[100vh] bg-red-300 flex flex-col gap-[15%] items-center pt-[21%]">
          <div>
            <Title/>
          </div>

          {children}
        </div>
      </div>
    </div>
       
      </body>
    </html>
  );
}
